#define LUA_COMPAT_5_1
#define LUA_COMPAT_5_2

// // Lua source code only, relative .
// #include "lapi.c"
// #include "lauxlib.c"
// #include "lbaselib.c"

// // Add all lua source file *.c, exclude lua.c, luac.c.//#include "$(LuaSrcRelativePath)/src/lua.c"//#include "$(LuaSrcRelativePath)/src/luac.c"
// #include "slua.c"

// #include "auxiliar.c"
// #include "buffer.c"
// #include "compat.c"
// #include "except.c"
// // #include "inet.c"
// #include "io.c"
// #include "lcode.c"
// #include "ldblib.c"
// #include "ldebug.c"
// #include "ldo.c"
// #include "ldump.c"
// #include "lfunc.c"
// #include "lgc.c"
// #include "linit.c"
// #include "liolib.c"
// #include "llex.c"
// #include "lmathlib.c"
// #include "lmem.c"
// #include "loadlib.c"
// #include "lobject.c"
// #include "lopcodes.c"
// #include "loslib.c"
// #include "lpack.c"
// #include "lparser.c"
// #include "lstate.c"
// #include "lstring.c"
// #include "lstrlib.c"
// #include "ltable.c"
// #include "ltablib.c"
// #include "ltm.c"
// // #include "luasocket.c"
// #include "lundump.c"
// #include "lvm.c"
// #include "lzio.c"
// #include "options.c"
// #include "print.c"
// #include "select.c"
// #include "tcp.c"
// #include "timeout.c"
// #include "udp.c"
// // #include "usocket.c"


#include "lapi.c"
#include "lauxlib.c"
#include "lbaselib.c"
#include "lcode.c"
#include "ldblib.c"
#include "ldebug.c"
#include "ldo.c"
#include "ldump.c"
#include "lfunc.c"
#include "lgc.c"
#include "linit.c"
#include "liolib.c"
#include "llex.c"
#include "lmathlib.c"
#include "lmem.c"
#include "loadlib.c"
#include "lobject.c"
#include "lopcodes.c"
#include "loslib.c"
#include "lparser.c"
#include "lstate.c"
#include "lstring.c"
#include "lstrlib.c"
#include "ltable.c"
#include "ltablib.c"
#include "ltm.c"
#include "lundump.c"
#include "lvm.c"
#include "lzio.c"
#include "slua.c"
#include "lpack.c"
// #include "luasocket.c"
// #include "i64lib.c"
//#include "memory_leak_checker.c"
// #include "pb.c"
// #include "lua_cjson.c"
// #include "fpconv.c"
// #include "strbuf.c"
// #include "xlua.c"