extern "C" {
#include "../../../../../xLua_WebGL/WebGLPlugins/lapi.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/lauxlib.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/lbaselib.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/lbitlib.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/lcode.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/lcorolib.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/lctype.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/ldblib.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/ldebug.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/ldo.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/ldump.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/lfunc.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/lgc.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/linit.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/liolib.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/llex.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/lmathlib.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/lmem.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/loadlib.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/lobject.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/lopcodes.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/loslib.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/lparser.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/lstate.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/lstring.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/lstrlib.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/ltable.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/ltablib.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/ltm.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/lundump.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/lutf8lib.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/lvm.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/lzio.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/i64lib.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/perflib.c"
#include "../../../../../xLua_WebGL/WebGLPlugins/xlua.c"
}



